version: '3.8'

services:
  nginx:
    container_name: nginx
    image: hershk17/cm-nginx:latest
    build:
      dockerfile: Dockerfile
      context: nginx
    ports:
      - 80:80
    depends_on:
      - client
      - server
    restart: always

  client:
    container_name: client
    image: hershk17/cm-client:latest
    build:
      dockerfile: Dockerfile
      context: src/client
    ports:
      - 5173:5173
    volumes:
      - ./src/client/src:/app
    restart: always

  server:
    container_name: server
    image: hershk17/cm-server:latest
    build:
      dockerfile: Dockerfile
      context: src/server
    environment:
      - NODE_ENV
      - MONGO_URI
      - JWT_SECRET
      - GOOGLE_CLIENT_ID
      - GOOGLE_CLIENT_SECRET
      - REACT_CLIENT_URL
      - EXPRESS_SERVER_URL
    ports:
      - 3000:3000
    restart: always