version: '3.8'

services:
  nginx:
    container_name: cm-nginx
    image: hershk17/cm-nginx:latest
    build:
      dockerfile: Dockerfile
      context: nginx
    ports:
      - 80:80
    depends_on:
      - client
      - server
    restart: always

  client:
    container_name: cm-client
    image: hershk17/cm-client:latest
    build:
      dockerfile: Dockerfile
      context: src/client
    environment:
      - NODE_ENV=${NODE_ENV}
      - CLIENT_URL=${CLIENT_URL}
      - SERVER_URL=${SERVER_URL}
    ports:
      - 5173:5173
    volumes:
      - ./src/client/src:/app/src
    restart: always

  server:
    container_name: cm-server
    image: hershk17/cm-server:latest
    build:
      dockerfile: Dockerfile
      context: src/server
    environment:
      - NODE_ENV=${NODE_ENV}
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - CLIENT_URL=${CLIENT_URL}
      - SERVER_URL=${SERVER_URL}
    ports:
      - 3000:3000
    restart: always