version: "3.8"

services:
  mongodb:
    container_name: mongodb
    image: mongo:5.0.2
    restart: always
    env_file: config/.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
    ports:
      - 27017:27017
    networks:
      - backend

  server:
    container_name: server
    restart: always
    depends_on:
      - mongodb
    build: src/server
    env_file: config/.env
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production
      - MONGO_URI_PROD
      - GOOGLE_CLIENT_ID
      - GOOGLE_CLIENT_SECRET
      - GOOGLE_CALLBACK_URL
      - JWT_SECRET_PROD
      - CLIENT_URL_PROD
      - SERVER_URL_PROD
    networks:
      - backend
      - frontend

  client:
    container_name: client
    restart: always
    depends_on:
      - server
    image: hershk17/content-manager-client:latest
    build:
      context: src/client
    ports:
      - 5173:5173
    environment:
      - NODE_ENV=production
      - REACT_APP_BASE_URL
    networks:
      - frontend 

networks:
  backend:
  frontend: