version: "3.8"

services:
  cm-client:
    container_name: cm-client
    restart: unless-stopped
    image: hershk17/content-manager-client:latest
    build:
      # src must be in context
      context: ./client
      dockerfile: docker/Dockerfile
    depends_on:
      - cm-server
    networks:
      - internal-client
    environment:
      - NODE_ENV=production
      # forwarded
      - REACT_APP_BASE_URL
    env_file:
      - ./client/.env

    # nginx ports
    ports:
      - "5173:80"

  cm-server:
    container_name: cm-server
    restart: unless-stopped
    image: hershk17/content-manager-server:latest
    build:
      context: ./server
      dockerfile: docker/Dockerfile
    depends_on:
      - cm-mongo
    environment:
      - NODE_ENV=production
      # forwarded
      - MONGO_URI_PROD
      - GOOGLE_CLIENT_ID
      - GOOGLE_CLIENT_SECRET
      - GOOGLE_CALLBACK_URL
      - JWT_SECRET_PROD
      - CLIENT_URL_PROD
      - SERVER_URL_PROD
    env_file:
      - ./server/.env
    networks:
      - default
      - internal-client

    # nginx ports
    ports:
      - "5000"

  cm-mongo:
    image: mongo:6.0.3
    container_name: cm-mongo
    restart: unless-stopped
    ports:
      - "27017"
    environment:
      # forwarded
      - MONGO_INITDB_DATABASE
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
    env_file:
      - ./server/.env
    volumes:
      - ./server/docker/mongo-data:/data/db
    networks:
      - default

networks:
  default:
    name: cm-default
  internal-client:
    name: cm-client
