version: '3.8'

services:
  nginx:
    container_name: cm-nginx
    image: cm-nginx
    build:
      dockerfile: Dockerfile
      context: nginx
    ports:
      - 80:80
    depends_on:
      - client
      - server
    restart: always

  client:
    container_name: cm-client
    image: cm-client
    build:
      dockerfile: Dockerfile
      context: src/client
    env_file: config/.env.${NODE_ENV}
    environment:
      - NODE_ENV=${NODE_ENV}
    ports:
      - 5173:5173
    volumes:
      - ./src/client/src:/app/src
    restart: always

  server:
    container_name: cm-server
    image: cm-server
    build:
      dockerfile: Dockerfile
      context: src/server
    env_file: config/.env.${NODE_ENV}
    environment:
      - NODE_ENV=${NODE_ENV}
    ports:
      - 3000:3000
    restart: always