version: "3.8"

services:
  nginx:
    container_name: nginx
    image: hershk17/cm-nginx:latest
    restart: always
    build:
      dockerfile: Dockerfile
      context: nginx
    ports:
      - 80:80
    depends_on:
      - client
      - server

  client:
    container_name: client
    image: hershk17/cm-client:latest
    build:
      dockerfile: Dockerfile
      context: src/client
    ports:
      - 5173:5173
    environment:
      - VITE_CLIENT_URL
      - VITE_SERVER_URL
    restart: always

  server:
    container_name: server
    image: hershk17/cm-server:latest
    build:
      dockerfile: Dockerfile
      context: src/server
    environment:
      - VITE_CLIENT_URL
      - VITE_SERVER_URL
      - MONGO_URI
      - GOOGLE_CLIENT_ID
      - GOOGLE_CLIENT_SECRET
      - FACEBOOK_CLIENT_ID
      - FACEBOOK_CLIENT_SECRET
      - STEAM_API_KEY
      - JWT_SECRET
    ports:
      - 3000:3000
    restart: always
