version: '3.4'

services:
  nginx:
    container_name: 'cm-nginx'
    image: 'sw-nginx'
    build:
      dockerfile: Dockerfile
      context: '../nginx'
    ports:
      - 80:80
    depends_on:
      - client
      - server
    restart: always

  client:
    container_name: 'cm-client'
    image: 'sw-client'
    build:
      dockerfile: Dockerfile
      context: '../src/client'
    ports:
      - 5173:5173
    volumes:
      - ../src/client/src:/app/src
    restart: always

  server:
    container_name: 'cm-server'
    image: 'sw-server'
    build:
      dockerfile: Dockerfile
      context: '../src/server'
    ports:
      - 3000:3000
    restart: always