name: Deploy DockerHub Images to AWS Elastic Beanstalk

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    name: Build, Tag, Push Docker Images to DockerHub
    uses: hershk17/content-manager/.github/workflows/build_images.yml@main
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v20
        env:
          SHA: ${{ github.sha }}
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: content-manager
          environment_name: cm-env
          version_label: $SHA
          region: us-east-1
          deployment_package: docker-compose-aws.yml
