name: Move assigned card
on:
  issues:
    types:
      - assigned
jobs:
  move-assigned-card:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.8.3
        with:
          project: Content Manager
          column: Todo
          repo-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
